# Generated by Django 3.0.2 on 2020-03-23 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diffName', models.CharField(max_length=200)),
                ('wordLenMin', models.PositiveIntegerField()),
                ('wordLenMax', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordName', models.CharField(max_length=200)),
                ('wordLen', models.PositiveIntegerField()),
                ('wordDif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangman.difficulty')),
            ],
        ),
    ]
