# Generated by Django 3.0.2 on 2020-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_category_stats_wordbankword'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catName',
            field=models.CharField(default='NULL', max_length=30),
            preserve_default=False,
        ),
    ]
