# Generated by Django 3.0.2 on 2020-04-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0008_auto_20200410_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='wordName',
            field=models.CharField(max_length=200),
        ),
    ]
