# Generated by Django 3.0.2 on 2020-04-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0009_auto_20200410_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='corLet',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='statDif',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hangman.difficulty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='wrongLet',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
